import { AnimatePresence, motion } from 'framer-motion'
import { CheckCircle2, ChevronLeft, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import Breadcrumbs from '../components/Breadcrumbs'
import { useShop } from '../context/ShopContext'
import { formatPrice } from '../components/ProductCard'

export default function CartPage() {
  const { cart, cartTotal, removeFromCart, updateQuantity } = useShop()
  const [checkoutOpen, setCheckoutOpen] = useState(false)
  if (!cart.length) return <main className="shell py-7 sm:py-10"><Breadcrumbs current="Корзина" /><div className="mx-auto max-w-md py-16 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-mist text-moss"><ShoppingBag size={33} /></div><h1 className="mt-6 text-2xl font-extrabold">Корзина пока пуста</h1><p className="mt-3 text-sm leading-6 text-slate-500">В каталоге найдётся всё для ваших тренировочных целей.</p><Link to="/catalog" className="button-primary mt-6">Выбрать товары</Link></div></main>
  return <main className="shell py-7 sm:py-10"><Breadcrumbs current="Корзина" /><h1 className="section-title">Корзина</h1><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="rounded-[22px] border border-line px-4 sm:px-6">{cart.map((item) => <div key={item.key} className="flex gap-3 border-b border-line py-5 last:border-none"><img src={item.product.image} alt="" className="h-24 w-24 rounded-xl bg-mist object-cover mix-blend-multiply sm:h-28 sm:w-28" /><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-moss">{item.product.brand}</p><Link to={`/product/${item.product.id}`} className="mt-1 block truncate text-sm font-bold hover:text-moss sm:text-base">{item.product.name}</Link><p className="mt-1 text-xs text-slate-500">{[item.flavor, item.size].filter(Boolean).join(' · ')}</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex h-9 items-center rounded-lg border border-line"><button type="button" onClick={() => updateQuantity(item.key, item.quantity - 1)} className="grid h-full w-9 place-items-center"><Minus size={15} /></button><span className="w-7 text-center text-xs font-bold">{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.key, item.quantity + 1)} className="grid h-full w-9 place-items-center"><Plus size={15} /></button></div><div className="flex items-center gap-4"><b className="text-sm">{formatPrice(item.product.price * item.quantity)}</b><button type="button" onClick={() => removeFromCart(item.key)} aria-label="Удалить товар" className="text-slate-400 hover:text-red-500"><Trash2 size={17} /></button></div></div></div></div>)}</div><aside className="h-fit rounded-[22px] bg-ink p-6 text-white lg:sticky lg:top-24"><h2 className="text-lg font-bold">Ваш заказ</h2><div className="mt-6 space-y-3 border-b border-white/10 pb-5 text-sm text-white/60"><div className="flex justify-between"><span>Товары</span><span>{formatPrice(cartTotal)}</span></div><div className="flex justify-between"><span>Доставка</span><span className="text-lime">Рассчитаем при оформлении</span></div></div><div className="mt-5 flex items-end justify-between"><span className="font-bold">Итого</span><span className="text-2xl font-extrabold tracking-[-.05em]">{formatPrice(cartTotal)}</span></div><button type="button" onClick={() => setCheckoutOpen(true)} className="button-primary mt-6 w-full">Оформить заказ</button><p className="mt-4 text-center text-[10px] leading-4 text-white/45">Это демо-оформление: оплата и передача данных не выполняются.</p></aside></div><Link to="/catalog" className="mt-7 inline-flex items-center gap-1 text-sm font-bold text-moss"><ChevronLeft size={16} />Продолжить покупки</Link><AnimatePresence>{checkoutOpen && <Checkout onClose={() => setCheckoutOpen(false)} />}</AnimatePresence></main>
}

function Checkout({ onClose }: { onClose: () => void }) {
  const [submitted, setSubmitted] = useState(false)
  const [delivery, setDelivery] = useState('Доставка')
  const [payment, setPayment] = useState('Kaspi')
  const { clearCart } = useShop()
  const submit = (event: FormEvent) => { event.preventDefault(); clearCart(); setSubmitted(true) }
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[70] grid place-items-center bg-ink/45 p-4 backdrop-blur-sm" onMouseDown={onClose}><motion.div initial={{ opacity: 0, y: 16, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 16, scale: .98 }} className="relative max-h-[90vh] w-full max-w-lg overflow-auto rounded-[28px] bg-white p-6 sm:p-8" onMouseDown={(event) => event.stopPropagation()}>{submitted ? <div className="py-9 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-mist text-lime"><CheckCircle2 size={42} /></div><h2 className="mt-6 text-3xl font-extrabold tracking-[-.05em]">Заказ принят</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-slate-500">Мы свяжемся с вами для подтверждения заказа. Спасибо, что выбрали Fit7Pro.</p><button type="button" onClick={onClose} className="button-primary mt-7">Вернуться к покупкам</button></div> : <form onSubmit={submit}><div className="flex items-start justify-between"><div><p className="eyebrow">Демо checkout</p><h2 className="text-2xl font-extrabold tracking-[-.05em]">Оформление заказа</h2></div><button type="button" onClick={onClose} className="icon-button">×</button></div><div className="mt-6 grid gap-3"><label className="text-xs font-bold">Имя<input required className="input mt-1.5" placeholder="Ваше имя" /></label><label className="text-xs font-bold">Телефон<input required type="tel" className="input mt-1.5" placeholder="+7 700 000 00 00" /></label><label className="text-xs font-bold">Город<input required className="input mt-1.5" defaultValue="Петропавловск" /></label><label className="text-xs font-bold">Адрес<input required className="input mt-1.5" placeholder="Улица, дом, квартира" /></label></div><Choice label="Способ получения" options={['Доставка', 'Самовывоз']} selected={delivery} onChange={setDelivery} /><Choice label="Способ оплаты" options={['Kaspi', 'Банковская карта', 'При получении']} selected={payment} onChange={setPayment} /><button className="button-primary mt-7 w-full">Подтвердить заказ</button></form>}</motion.div></motion.div>
}
function Choice({ label, options, selected, onChange }: { label: string; options: string[]; selected: string; onChange: (value: string) => void }) { return <fieldset className="mt-5"><legend className="text-xs font-bold">{label}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{options.map((option) => <button key={option} type="button" onClick={() => onChange(option)} className={`rounded-xl border p-3 text-left text-xs font-bold transition ${selected === option ? 'border-lime bg-mist text-moss' : 'border-line'}`}>{option}</button>)}</div></fieldset> }
