import { motion } from 'framer-motion'
import { Heart, Minus, Plus, ShieldCheck, ShoppingBag, Star, Truck } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { Link, useParams } from 'react-router-dom'
import Breadcrumbs from '../components/Breadcrumbs'
import ProductCard, { formatPrice } from '../components/ProductCard'
import { products } from '../data/catalog'
import { useShop } from '../context/ShopContext'

export default function ProductPage() {
  const { id } = useParams()
  const product = products.find((candidate) => candidate.id === id)
  const { addToCart, favorites, toggleFavorite, setCartOpen } = useShop()
  const [activeImage, setActiveImage] = useState(0)
  const [size, setSize] = useState(product?.sizes[0] ?? '')
  const [flavor, setFlavor] = useState(product?.flavors?.[0] ?? '')
  const [quantity, setQuantity] = useState(1)
  const [tab, setTab] = useState<'description' | 'facts' | 'reviews'>('description')
  if (!product) return <main className="shell py-20 text-center"><h1 className="section-title">Товар не найден</h1><Link to="/catalog" className="button-primary mt-6">Вернуться в каталог</Link></main>
  const add = (openCart = false) => { addToCart(product, size, flavor, quantity); if (openCart) setCartOpen(true) }
  const isFavorite = favorites.includes(product.id)
  const related = products.filter((candidate) => candidate.category === product.category && candidate.id !== product.id).slice(0, 4)

  return <main className="shell py-7 sm:py-10"><Breadcrumbs parent={['Каталог', '/catalog']} current={product.name} /><div className="grid gap-8 lg:grid-cols-[minmax(0,1.05fr)_minmax(390px,.95fr)] lg:gap-14">
    <div><div className="relative aspect-square overflow-hidden rounded-[28px] bg-[#f5f8f5]"><motion.img key={activeImage} initial={{ opacity: .35, scale: 1.03 }} animate={{ opacity: 1, scale: 1 }} src={product.images[activeImage]} alt={`${product.brand} ${product.name}`} className="h-full w-full object-cover mix-blend-multiply" />{product.badge && <span className="badge absolute left-5 top-5 bg-lime text-white">{product.badge}</span>}</div><div className="mt-3 flex gap-3">{product.images.map((image, index) => <button key={image} type="button" onClick={() => setActiveImage(index)} className={`h-16 w-16 overflow-hidden rounded-xl border-2 bg-mist transition ${activeImage === index ? 'border-lime' : 'border-transparent'}`}><img src={image} alt={`Фото ${index + 1}`} className="h-full w-full object-cover mix-blend-multiply" /></button>)}</div></div>
    <div className="lg:pt-2"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-moss">{product.brand}</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-.055em] sm:text-4xl">{product.name}</h1><div className="mt-4 flex items-center gap-2 text-sm"><span className="flex items-center gap-1 rounded-full bg-[#fff8e8] px-2.5 py-1 font-bold"><Star size={15} fill="#f6b838" strokeWidth={0} />{product.rating.toFixed(1)}</span><button type="button" onClick={() => setTab('reviews')} className="text-slate-500 underline underline-offset-4">{product.reviews} отзывов</button><span className={product.inStock ? 'ml-1 text-xs font-bold text-moss' : 'ml-1 text-xs font-bold text-red-500'}>{product.inStock ? 'В наличии' : 'Нет в наличии'}</span></div><div className="mt-7 flex items-end gap-3"><span className="text-4xl font-extrabold tracking-[-.065em]">{formatPrice(product.price)}</span>{product.oldPrice && <del className="pb-1 text-base text-slate-400">{formatPrice(product.oldPrice)}</del>}</div>
      {product.flavors && <OptionGroup label="Вкус" value={flavor} options={product.flavors} onChange={setFlavor} />}{<OptionGroup label="Объём" value={size} options={product.sizes} onChange={setSize} />}
      <div className="mt-7 flex gap-3"><div className="flex h-12 items-center rounded-xl border border-line"><button onClick={() => setQuantity((value) => Math.max(1, value - 1))} type="button" className="grid h-full w-11 place-items-center" aria-label="Уменьшить количество"><Minus size={17} /></button><span className="w-7 text-center text-sm font-bold">{quantity}</span><button onClick={() => setQuantity((value) => value + 1)} type="button" className="grid h-full w-11 place-items-center" aria-label="Увеличить количество"><Plus size={17} /></button></div><motion.button whileTap={{ scale: .98 }} disabled={!product.inStock} type="button" onClick={() => add()} className="button-primary flex-1 disabled:cursor-not-allowed disabled:bg-slate-300"><ShoppingBag size={17} />Добавить в корзину</motion.button><button type="button" onClick={() => toggleFavorite(product.id)} className={`icon-button h-12 w-12 border-line ${isFavorite ? 'border-lime bg-mist text-lime' : ''}`} aria-label="Добавить в избранное"><Heart size={20} fill={isFavorite ? 'currentColor' : 'none'} /></button></div><button type="button" onClick={() => add(true)} disabled={!product.inStock} className="button-dark mt-3 w-full disabled:bg-slate-300">Купить сейчас</button>
      <div className="mt-7 grid gap-3 border-t border-line pt-6 sm:grid-cols-2"><ProductBenefit icon={<Truck size={18} />} title="Доставка или самовывоз" text="Выберите способ при оформлении." /><ProductBenefit icon={<ShieldCheck size={18} />} title="Качественные товары" text="Информация и состав на странице." /></div></div>
  </div>
  <section className="mt-14 border-t border-line pt-10 sm:mt-20"><div className="no-scrollbar flex gap-5 overflow-x-auto border-b border-line">{([['description', 'Описание'], ['facts', 'Характеристики и состав'], ['reviews', `Отзывы (${product.reviews})`]] as const).map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`whitespace-nowrap border-b-2 px-1 pb-4 text-sm font-bold transition ${tab === key ? 'border-lime text-moss' : 'border-transparent text-slate-500'}`}>{label}</button>)}</div><div className="max-w-3xl py-8">{tab === 'description' && <div className="text-sm leading-7 text-slate-600"><p>{product.description}</p><h3 className="mt-6 text-base font-extrabold text-ink">Способ применения</h3><p className="mt-2">{product.use}</p></div>}{tab === 'facts' && <div className="grid gap-7 sm:grid-cols-2"><div><h3 className="text-base font-extrabold">Характеристики</h3><dl className="mt-3">{product.characteristics.map(([label, value]) => <div key={label} className="flex justify-between gap-5 border-b border-line py-3 text-sm"><dt className="text-slate-500">{label}</dt><dd className="text-right font-semibold">{value}</dd></div>)}</dl></div><div><h3 className="text-base font-extrabold">Состав</h3><p className="mt-3 text-sm leading-7 text-slate-600">{product.ingredients}</p></div></div>}{tab === 'reviews' && <div className="rounded-2xl bg-[#fbfdfb] p-5"><div className="flex items-center gap-4"><div className="font-display text-4xl tracking-[-.09em]">{product.rating.toFixed(1)}</div><div><div className="flex text-[#f6b838]">{Array.from({ length: 5 }, (_, index) => <Star key={index} size={17} fill="currentColor" strokeWidth={0} />)}</div><p className="mt-1 text-xs text-slate-500">На основе {product.reviews} отзывов · демо-данные</p></div></div><div className="mt-6 border-t border-line pt-5"><p className="text-sm font-bold">Отличный продукт</p><p className="mt-2 text-sm leading-6 text-slate-600">Удобно выбрать нужный вкус и объём. Качественная демонстрация отзыва для макета магазина.</p></div></div>}</div></section>
  {related.length > 0 && <section className="mt-8 border-t border-line pt-12 sm:mt-14"><h2 className="section-title text-3xl">С этим покупают</h2><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{related.map((relatedProduct, index) => <ProductCard key={relatedProduct.id} product={relatedProduct} index={index} />)}</div></section>}
  </main>
}

function OptionGroup({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <div className="mt-6"><div className="mb-3 text-sm font-bold">{label}: <span className="font-medium text-slate-500">{value}</span></div><div className="flex flex-wrap gap-2">{options.map((option) => <button key={option} type="button" onClick={() => onChange(option)} className={`rounded-xl border px-3 py-2 text-sm font-semibold transition ${option === value ? 'border-lime bg-mist text-moss' : 'border-line hover:border-moss'}`}>{option}</button>)}</div></div> }
function ProductBenefit({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="flex gap-3"><span className="text-moss">{icon}</span><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[11px] leading-4 text-slate-500">{text}</p></div></div> }
