import { AnimatePresence, motion } from 'framer-motion'
import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CloseButton, useShop } from '../context/ShopContext'
import { formatPrice } from './ProductCard'

export default function CartDrawer() {
  const { cart, cartOpen, setCartOpen, cartTotal, updateQuantity, removeFromCart } = useShop()
  return <AnimatePresence>{cartOpen && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[65] bg-ink/35 backdrop-blur-sm" onMouseDown={() => setCartOpen(false)}>
    <motion.aside initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'tween', duration: .3, ease: [0.22, 1, 0.36, 1] }} className="ml-auto flex h-full w-full max-w-[460px] flex-col bg-white" onMouseDown={(event) => event.stopPropagation()} aria-label="Корзина">
      <div className="flex items-center justify-between border-b border-line px-5 py-5 sm:px-7"><div><h2 className="text-xl font-extrabold tracking-[-.04em]">Корзина</h2><p className="mt-1 text-xs text-slate-500">{cart.length ? `${cart.length} ${cart.length === 1 ? 'товар' : 'товара'} в заказе` : 'Пока здесь пусто'}</p></div><CloseButton onClick={() => setCartOpen(false)} /></div>
      {cart.length === 0 ? <div className="m-auto max-w-xs px-6 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-mist text-moss"><ShoppingBag size={28} /></div><h3 className="mt-5 text-lg font-bold">Ваша корзина пуста</h3><p className="mt-2 text-sm leading-6 text-slate-500">Добавьте то, что поможет вам приблизиться к своей цели.</p><Link onClick={() => setCartOpen(false)} to="/catalog" className="button-primary mt-6">Перейти в каталог</Link></div> : <>
        <div className="no-scrollbar flex-1 overflow-y-auto px-5 py-5 sm:px-7">{cart.map((item) => <div key={item.key} className="flex gap-3 border-b border-line py-4 first:pt-0"><img src={item.product.image} alt="" className="h-20 w-20 rounded-xl bg-mist object-cover mix-blend-multiply" /><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-moss">{item.product.brand}</p><p className="mt-1 truncate text-sm font-bold">{item.product.name}</p><p className="mt-1 text-xs text-slate-500">{[item.flavor, item.size].filter(Boolean).join(' · ')}</p><div className="mt-3 flex items-center justify-between"><div className="flex h-8 items-center rounded-lg border border-line"><button type="button" onClick={() => updateQuantity(item.key, item.quantity - 1)} className="grid h-full w-8 place-items-center" aria-label="Уменьшить количество"><Minus size={14} /></button><span className="w-7 text-center text-xs font-bold">{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.key, item.quantity + 1)} className="grid h-full w-8 place-items-center" aria-label="Увеличить количество"><Plus size={14} /></button></div><div className="flex items-center gap-2"><b className="text-sm">{formatPrice(item.product.price * item.quantity)}</b><button type="button" onClick={() => removeFromCart(item.key)} aria-label="Удалить товар" className="text-slate-400 transition hover:text-red-500"><Trash2 size={16} /></button></div></div></div></div>)}</div>
        <div className="border-t border-line bg-[#fbfdfb] p-5 sm:p-7"><div className="mb-4 rounded-xl bg-mist px-3 py-2.5 text-xs font-semibold text-moss">Бесплатная доставка по городу от 25 000 ₸</div><div className="flex justify-between text-sm text-slate-500"><span>Товары</span><span>{formatPrice(cartTotal)}</span></div><div className="mt-3 flex items-end justify-between"><span className="text-lg font-bold">Итого</span><motion.span key={cartTotal} initial={{ scale: 1.08 }} animate={{ scale: 1 }} className="text-2xl font-extrabold tracking-[-.05em]">{formatPrice(cartTotal)}</motion.span></div><Link onClick={() => setCartOpen(false)} to="/cart" className="button-primary mt-5 w-full">Оформить заказ</Link></div>
      </>}
    </motion.aside>
  </motion.div>}</AnimatePresence>
}
